name: ToyDB CI Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./toy-db

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Run Regular Tests (All Branches).
      run: make test-native

    - name: Run Concurrency Stress Tests (PRs Only)
      if: github.event_name == 'pull_request'
      run: make test-stress-native